spring.application.name=demo

spring.datasource.url=jdbc:postgresql://postgres:5432/UsersDB
spring.datasource.username=ODanylchuk
spring.datasource.password=some_awesome_password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=rabbitmq.default.svc.cluster.local
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

queue.name=order-created-queue
exchange.name=order-exchange
routing.key=order.created

keycloak.auth-server-url=http://microservices.local:8080/realms/MyRealm
keycloak.realm=MyRealm
keycloak.resource=users-microservice
keycloak.public-client=true
keycloak.ssl-required=none

springdoc.swagger-ui.oauth-client-id=users-microservice
springdoc.swagger-ui.oauth-realm=MyRealm
springdoc.swagger-ui.oauth-app-name=Keycloak-protected-API
springdoc.swagger-ui.oauth-use-pkce=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/MyRealm/protocol/openid-connect/certs

logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG