apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: tasks
  name: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tasks
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: tasks
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://:@db:5432/tasksms
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: PGUSER
                  name: env
            - name: PG_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: PG_PASSWORD
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: PG_USER
          image: melmn/tasks:latest
          name: tasks
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
